In [5]:
import babypandas as bpd

In [7]:
weather = bpd.DataFrame().assign(
    city=['La Jolla', 'San Diego', 'Austin', 'Los Angeles'],
    state=['California', 'California', 'Texas', 'California'],
    today_high_temp=['79', '83', '87', '87']
    
)

schools = bpd.DataFrame().assign(
    name=['UCSD', 'University of Chicago', 'University of San Diego','Johns Hopkins University', 'UT Austin', 'SDSU', 'UCLA'], 
    city=['La Jolla', 'Chicago', 'San Diego', 'Baltimore', 'Austin', 'San Diego', 'Los Angeles'],
    state=['California', 'Illinois', 'California', 'Maryland', 'Texas', 'California', 'California'],
    graduation_rate=[0.87, 0.94, 0.78, 0.92, 0.81, 0.83, 0.91 ]
)

In [8]:
weather

          city       state today_high_temp
0     La Jolla  California              79
1    San Diego  California              83
2       Austin       Texas              87
3  Los Angeles  California              87

In [9]:
schools

                       name         city       state  graduation_rate
0                      UCSD     La Jolla  California             0.87
1     University of Chicago      Chicago    Illinois             0.94
2   University of San Diego    San Diego  California             0.78
3  Johns Hopkins University    Baltimore    Maryland             0.92
4                 UT Austin       Austin       Texas             0.81
5                      SDSU    San Diego  California             0.83
6                      UCLA  Los Angeles  California             0.91

In [10]:
weather.merge(schools, on='city')

,city,state_x,today_high_temp,name,state_y,graduation_rate
0,La Jolla,California,79,UCSD,California,0.87
1,San Diego,California,83,University of San Diego,California,0.78
2,San Diego,California,83,SDSU,California,0.83
3,Austin,Texas,87,UT Austin,Texas,0.81
4,Los Angeles,California,87,UCLA,California,0.91

Get the data from here: https://library.ucsd.edu/dc/object/bb4003017c
Need to delete the first several rows before running this notebook

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('temp.csv')
df = df[['YEAR', 'MONTH', 'DAY', 'SURF_TEMP_C']]
df = df.dropna()
df

       YEAR  MONTH  DAY  SURF_TEMP_C
0      1916      8   22         19.5
1      1916      8   23         19.9
2      1916      8   24         19.7
3      1916      8   25         19.7
4      1916      8   26         19.5
...     ...    ...  ...          ...
39755  2025      6   26         22.4
39756  2025      6   27         21.5
39757  2025      6   28         22.1
39758  2025      6   29         21.7
39759  2025      6   30         20.4

[38443 rows x 4 columns]

In [3]:
df.columns = ['YEAR', 'MONTH', 'DAY', 'SURFACE_TEMP']

In [4]:
df.to_csv('../data/sea_temp.csv', index=False)