In [1]:
import pandas as pd
import numpy as np

Download the roster in "standard format", remove the first few rows in Google sheets, and save as a CSV). **Don't** commit the roster to GitHub – let's avoid the possibility of accidentally releasing it to students.

In [2]:
roster = pd.read_csv('enrolled.csv')

In [3]:
roster['Sec ID'].value_counts()

915848    156
915854    138
915851    136
980797     64
Name: Sec ID, dtype: int64

In [4]:
roster['Lecture'] = roster['Sec ID'].replace({
    915848: 'A',
    915851: 'B',
    915854: 'C',
    980797: 'D'
})

In [12]:
roster.sample(10)

,Sec ID,PID,Student,Pronoun,Credits,College,Major,Level,Email,Lecture
318,915851,A19294193,"Parveez, Rayyan",NaN,4,RE,DS25,JR,rparveez@ucsd.edu,B
217,915851,A18740233,"Le, Devin",He/Him,4,MU,MA35,FR,del037@ucsd.edu,B
255,915848,A19063689,"Liu, Shuhan",She/Her,4,MU,UNSS,FR,shl210@ucsd.edu,A
12,915848,A18901472,"Amatya, Medha",NaN,4,SI,DS25,SO,mamatya@ucsd.edu,A
367,915854,A19171245,"Shiu, Justin",He/Him,4,SN,DS25,SR,jrshiu@ucsd.edu,C
76,915848,A18706203,"Crosby, Bennett",NaN,4,RE,DS25,FR,bpcrosby@ucsd.edu,A
470,915848,A19148309,"Yu, Samuel",NaN,4,TH,DS25,JR,say014@ucsd.edu,A
239,915851,A18751562,"Lim, Nathan",NaN,4,EI,DS25,SO,njlim@ucsd.edu,B
102,915851,A19289318,"Enkhamgalan, Tuvshinzaya",NaN,4,RE,EN30,JR,tenkhamgalan@ucsd.edu,B
337,915854,A18769675,"Prasad, Laksha",She/Her,4,MU,DS25,FR,lprasad@ucsd.edu,C

In [13]:
roster['Student'] = (roster['Student'].str.split().str[-1] + ' ' + 
                     list(map(lambda x: ''.join(x), np.random.choice(list('abcdefghijklmnopqrstuvwxyz'), 
                                                                     size=(roster.shape[0], 6)))))
roster['Student'] = roster['Student'].str.title()
roster

,Sec ID,PID,Student,Pronoun,Credits,College,Major,Level,Email,Lecture
0,915848,A17317021,Atef Qxaoyd,NaN,4,SN,EN28,JR,atabdullah@ucsd.edu,A
1,915848,A19284882,Rami Vepflq,NaN,4,MU,DS25,JR,rabukhater@ucsd.edu,A
2,915848,A19232039,Alan Cqwtbv,NaN,4,WA,DS25,FR,ala036@ucsd.edu,A
3,915848,A19241934,Jonathan Hwseeb,NaN,4,TH,DS25,JR,jladrian@ucsd.edu,A
4,915848,A19149974,Aryan Zoavnf,NaN,4,FI,DS25,SR,ara030@ucsd.edu,A
...,...,...,...,...,...,...,...,...,...,...
489,915848,A18616372,Ziyong Kutlrm,NaN,4,TH,CG33,JR,ziz151@ucsd.edu,A
490,915854,A17767915,Minqi Plasjl,NaN,4,TH,EN28,SR,miz037@ucsd.edu,C
491,980797,A19230903,Travis Qzhqdy,NaN,4,RE,DS25,SO,tyzhu@ucsd.edu,D
492,980797,A18872608,Yuting Ekriyh,She/Her,4,TH,DS25,FR,yuz391@ucsd.edu,D
493,980797,A19291032,Leo Jyhibk,NaN,4,MU,DS25,SR,lzubiate@ucsd.edu,D

In [14]:
roster = roster.get(['Student', 'Lecture'])
roster.columns=['name', 'section']
roster

                name section
0        Atef Qxaoyd       A
1        Rami Vepflq       A
2        Alan Cqwtbv       A
3    Jonathan Hwseeb       A
4       Aryan Zoavnf       A
..               ...     ...
489    Ziyong Kutlrm       A
490     Minqi Plasjl       C
491    Travis Qzhqdy       D
492    Yuting Ekriyh       D
493       Leo Jyhibk       D

[494 rows x 2 columns]

In [20]:
roster = roster.sample(frac=1).reset_index(drop=True) # So it's not alphabetically sorted
roster

                name section
0     Camilla Ozqcfu       B
1       Yifan Ignjpe       A
2         Ali Jjsojh       A
3     Hirkani Pkjcfr       D
4        Veda Grxlem       B
..               ...     ...
489        An Pxidlp       B
490      Dora Uutxls       B
491  Qiankang Tzjsbb       D
492       Kim Wxnmuh       C
493   Jazmine Sxcvft       C

[494 rows x 2 columns]

In [21]:
roster.to_csv('../data/roster-anon.csv', index=False)

In [22]:
def first_name(full_name):
    return full_name.split(' ')[0]

In [23]:
with_first = roster.assign(first=roster['name'].apply(first_name))

In [24]:
first_counts = with_first.groupby('first').count().sort_values('name', ascending=False)

In [25]:
def how_many_others_in_section(name):
    row = with_first[roster['name'] == name]
    first = row.get('first').iloc[0]
    section = row.get('section').iloc[0]
    return with_first[(with_first.get('section') == section) & (with_first.get('first') == first)].shape[0]

In [26]:
with_others = with_first.assign(others=with_first.get('name').apply(how_many_others_in_section))
with_others

                name section     first  others
0     Camilla Ozqcfu       B   Camilla       1
1       Yifan Ignjpe       A     Yifan       1
2         Ali Jjsojh       A       Ali       2
3     Hirkani Pkjcfr       D   Hirkani       1
4        Veda Grxlem       B      Veda       1
..               ...     ...       ...     ...
489        An Pxidlp       B        An       1
490      Dora Uutxls       B      Dora       1
491  Qiankang Tzjsbb       D  Qiankang       1
492       Kim Wxnmuh       C       Kim       1
493   Jazmine Sxcvft       C   Jazmine       1

[494 rows x 4 columns]

In [27]:
with_others[with_others.get('others') > 1].sort_values('others', ascending=False)

                   name section        first  others
486       Joseph Jpoelz       C       Joseph       4
411       Joseph Vdhfyo       C       Joseph       4
329       Joseph Jaqwhh       C       Joseph       4
323       Joseph Iruyxy       C       Joseph       4
204        Ethan Cdmvct       A        Ethan       3
461         Noah Adekar       B         Noah       3
405         Noah Ebjtzc       B         Noah       3
399        Ethan Cibofj       A        Ethan       3
320       Daniel Qoxuob       B       Daniel       3
257       Andrew Iduhph       B       Andrew       3
225       Andrew Uwpdum       B       Andrew       3
300        Ethan Spzixe       A        Ethan       3
69        Daniel Rzxpbf       B       Daniel       3
107         Noah Rkmhax       B         Noah       3
34        Andrew Ytwzqs       B       Andrew       3
63        Daniel Mvwxdd       B       Daniel       3
404  Christopher Ynkjng       B  Christopher       2
354       Justin Liccdx       C       Justin       2
373       Tianle Pciqwx       C       Tianle       2
375       Tianle Yaxqos       C       Tianle       2
384        Dylan Nvscni       A        Dylan       2
58       Kaitlyn Neucdm       B      Kaitlyn       2
340         Minh Fggyng       C         Minh       2
438          Max Qacxgt       C          Max       2
446      Matthew Pwpgqa       C      Matthew       2
447      Matthew Fphpip       C      Matthew       2
458         Lana Rfixqr       C         Lana       2
17           Max Qzounn       C          Max       2
346      Michael Nuhlbd       B      Michael       2
188      Michael Xowwhb       B      Michael       2
224       Andrew Hedowv       D       Andrew       2
84       Kaitlyn Npzkqj       B      Kaitlyn       2
317  Christopher Gljafi       B  Christopher       2
315        James Fiefsg       C        James       2
306         Lana Ohznlv       C         Lana       2
7          James Hfjghx       C        James       2
291       Andrew Olkgvs       D       Andrew       2
284          Ali Wccqhw       A          Ali       2
280         Minh Cpjhrr       C         Minh       2
260        Dylan Mhfmpy       A        Dylan       2
149       Jayden Cnyiyu       B       Jayden       2
251       Justin Agyaex       C       Justin       2
231      William Fqrypi       D      William       2
226      William Mjsrep       D      William       2
154       Jayden Lcaert       B       Jayden       2
2            Ali Jjsojh       A          Ali       2

In [28]:
for_last_slide = with_first.groupby(['first', 'section']).count().sort_values('name', ascending=False).reset_index()
for_last_slide[for_last_slide.get('name')>1]

          first section  name
0        Joseph       C     4
1          Noah       B     3
2        Andrew       B     3
3         Ethan       A     3
4        Daniel       B     3
5   Christopher       B     2
6        Jayden       B     2
7          Minh       C     2
8           Ali       A     2
9           Max       C     2
10      Michael       B     2
11        James       C     2
12       Justin       C     2
13       Tianle       C     2
14         Lana       C     2
15      Kaitlyn       B     2
16      William       D     2
17        Dylan       A     2
18      Matthew       C     2
19       Andrew       D     2